### ISSUE TITLE
On Node.js v6.11, NPM install didn't work

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [anandanand84/technicalindicators#102]
On Node.js v6.11, NPM install didn't work.
Of course, on Node.js v8.9.4(current LTS  version) it works.

**Comment by anandanand84** [comment]
what is the error you are getting?

**Comment by LoveMeWithoutAll** [comment]
Follow error msg

```bash
/home/ubuntu/workspace/node_modules/keras-js/lib/Model.js:107
  async _initialize() {
        ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/keras-js/lib/index.js:22:37)
```

It occured both Windows7 and Ubuntu Linux.
You can see on [c9 link(ubuntu)](https://ide.c9.io/youngsun/npm-test) at node.js V6.11.2

**Comment by anandanand84** [comment]
Caused by https://github.com/transcranial/keras-js/issues/103

**Comment by LoveMeWithoutAll** [comment]
It works well. Thanks a lot!
