### ISSUE TITLE
Problem in ionic3

### ISSUE THREAD

**Issue by ourarash** [anandanand84/technicalindicators#107]
I am using this in ionic 2. Here is my code:

`import { SMA } from "technicalindicators";
let r = SMA.calculate({ period: p, values: this.y });
`

`TypeError: t.resolve is not a function
    at Object.setNativePromise (http://localhost:8100/build/polyfills.js:3:18280)
    at L.configurable.L.set (http://localhost:8100/build/polyfills.js:3:23002)
    at module.exports (http://localhost:8100/build/vendor.js:41452:12)
    at $export (http://localhost:8100/build/vendor.js:21403:17)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:337500:1)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:334898:1)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:334776:1)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:334785:30)`

**Comment by anandanand84** [comment]
@ourarash not sure how I can help, Looks like you are using webpack, did you try this from the readme in your webpack config.

```
module.exports = {
  resolve: {
    mainFields: ["module", "main"]
  }
}
```

**Comment by ourarash** [comment]
Yes ionic uses webpack. That  didn't seem to work. Thanks for the answer though.

**Comment by anandanand84** [comment]
@ourarash can you create a simple app which I can test, you can see if https://github.com/anandanand84/react-technicalindicators helps
