### ISSUE TITLE
Not able to install on local

### ISSUE THREAD

**Issue by saurabh-vijayvargiya** [anandanand84/technicalindicators#154]
Hi,

I followed the below process to download and install the project.

```
npm install -g typescript@2.0.0
git clone git@github.com:anandanand84/technicalindicators.git  # or use your fork
cd technicalindicators
npm run start
```
Also installled canvas before all this. But in the end while running the project I am getting this error -

```
03:48:07 - Starting compilation in watch mode...



src/patterndetection/patterndetection.ts(3,21): error TS2307: Cannot find module '@tensorflow/tfjs'.
03:48:14 - Compilation complete. Watching for file changes.


Error: Cannot find module '@tensorflow/tfjs'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)

    at Object.<anonymous> (/src/dist/index.js:6:10)
    at Module._compile (module.js:641:30)
    at loader (/src/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/src/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/test/chart_types/Renko.js:5:13)
    at Module._compile (module.js:641:30)
    at loader (/src/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/src/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /src/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/src/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/src/node_modules/mocha/lib/mocha.js:469:10)
```

I am installing this on Mac OS high sierra.

If I missed any crucial detail about the bug then please let me know.

Thanks

**Comment by ManuCart** [comment]
just try
````
mkdir technicalindicators
cd technicalindicators
npm install technicalindicators
````

**Comment by saurabh-vijayvargiya** [comment]
@ManuCart Thanks it worked.
