### ISSUE TITLE
Registration of backend tensorflow failed Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by bengrunfeld** [anandanand84/technicalindicators#162]
Running on Amazon Web Services via Elastic Beanstalk.

System information:

    Linux ip-172-31-30-251 4.14.88-72.76.amzn1.x86_64 #1 SMP Mon Jan 7 19:47:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Error:

```
Nodejs Environment detected 
Registration of backend tensorflow failed
Error: Could not locate the bindings file. Tried:
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/build/tfjs_binding.node
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/build/Debug/tfjs_binding.node
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/build/Release/tfjs_binding.node
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/out/Debug/tfjs_binding.node
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/Debug/tfjs_binding.node
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/out/Release/tfjs_binding.node
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/Release/tfjs_binding.node
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/build/default/tfjs_binding.node
 â†’ /var/app/current/node_modules/@tensorflow/tfjs-node/compiled/10.15.0/linux/x64/tfjs_binding.node
    at bindings (/var/app/current/node_modules/bindings/bindings.js:96:9)
    at /var/app/current/node_modules/@tensorflow/tfjs-node/dist/index.js:11:60
    at Environment.registerBackend (/var/app/current/node_modules/@tensorflow/tfjs-core/dist/environment.js:210:27)
    at Object.<anonymous> (/var/app/current/node_modules/@tensorflow/tfjs-node/dist/index.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
Prod: App listening to 8081....
Press Ctrl+C to quit.

============================
Hi there ðŸ‘‹. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================
```

**Comment by willoughby** [comment]
Did you resolve this ?

**Comment by bengrunfeld** [comment]
@willoughby Unfortunately not. As a result, I had to switch to [Tulind](https://www.npmjs.com/package/tulind), which had its own set of errors with AWS EB, but I was able to [solve those](https://github.com/TulipCharts/tulipnode/issues/50).

**Comment by anandanand84** [comment]
Tensorflow removed in 3.0. It should work now
