### ISSUE TITLE
Cannot install - canvas binares not found error

### ISSUE THREAD

**Issue by Deca** [anandanand84/technicalindicators#164]
Hi,
I've git cloned the repo on my pc (running win 10 with node 10.x) but when I try to run "npm install" I get this error:

```
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.16/canvas-prebuilt-v2.0.0-alpha.16-node-v64-win32-unknown-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for canvas@2.0.0-alpha.16 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
```

I've tried to install a recent version of canvas with `npm install canvas@2.2.0` but I get the same error and I don't understand why it still search for the 2.0.0 alpha

**Comment by anandanand84** [comment]
Canvas is only a dev dependency. It is required only for tests to verify if candlestick patterns are working properly. Are you trying to develop or running tests?

**Comment by anandanand84** [comment]
If you still face this issue. Please reopen. Canvas is only a dev dependency to run tests. Le met also the OS you are using.

**Comment by murilo-campaner** [comment]
I'm with same problem in Mac OS Mojave.
Trying to develop.

**Comment by murilo-campaner** [comment]
```gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@12.8.1 | darwin | x64
gyp info find Python using Python version 2.7.15 found at "/usr/local/opt/python@2/bin/python2.7"
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/murilocampaner/Code/technicalindicators/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/murilocampaner/Library/Caches/node-gyp/12.8.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/murilocampaner/Library/Caches/node-gyp/12.8.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/murilocampaner/Library/Caches/node-gyp/12.8.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/murilocampaner/Code/technicalindicators',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /Users/murilocampaner/Code/technicalindicators) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/11.7.0/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/murilocampaner/Code/technicalindicators
gyp ERR! node -v v12.8.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok ```
