### ISSUE TITLE
Issues with installation on ubuntu

### ISSUE THREAD

**Issue by Rakesh-gene** [anandanand84/technicalindicators#172]
Exception has occurred: Error
Error: ENOENT: no such file or directory, access '/api/node_modules/technicalindicators/node_modules/@tensorflow/tfjs-node/dist/package.json'
    at Object.fs.accessSync (fs.js:301:11)
    at exists (/api/node_modules/bindings/bindings.js:10:60)
    at Function.getRoot (/api/node_modules/bindings/bindings.js:161:9)
    at bindings (/api/node_modules/bindings/bindings.js:60:32)
    at /api/node_modules/technicalindicators/node_modules/@tensorflow/tfjs-node/dist/index.js:11:60
    at Environment.registerBackend (/api/node_modules/technicalindicators/node_modules/@tensorflow/tfjs-core/dist/environment.js:210:27)
    at Object.<anonymous> (/api/node_modules/technicalindicators/node_modules/@tensorflow/tfjs-node/dist/index.js:10:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

Getting the above error while trying to use in a JS file

**Comment by anandanand84** [comment]
Tensorflow removed in 3.0. It should work now
