### ISSUE TITLE
Can this work with React Native?

### ISSUE THREAD

**Issue by whittlem** [anandanand84/technicalindicators#173]
Does "technicalindicators" work with React Native?

I installed it with:
"yum add technicalindicators"

And have tried loading the library with these:
import { SMA } from 'technicalindicators';
import SMA from 'technicalindicators';
const { SMA } = require('technicalindicators');

I am getting this error message:

error: bundling failed: Error: Unable to resolve module `path` from `app/node_modules/technicalindicators/dist/index.js`: Module `path` does not exist in the Haste module map

Any ideas?

**Comment by whittlem** [comment]
I installed the "path" and "fs" dependencies...

yarn add path
yarn add fs

And now getting this error message:

error: bundling failed: Error: While trying to resolve module `fs` from file `app/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js`, the package `app/node_modules/fs/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`app/node_modules/fs/index.js`. Indeed, none of these files exist:

  * `app/node_modules/fs/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `app/node_modules/fs/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (app/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (app/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)

**Comment by anandanand84** [comment]
It should work. If you cannot add it as part of build. You can use the built .js file from https://github.com/anandanand84/technicalindicators/tree/master/dist

**Comment by whittlem** [comment]
Thanks, I will try that. Do you have an example on how I can include this js file and which one do I include?

**Comment by whittlem** [comment]
@anandanand84, any news with this?

**Comment by anandanand84** [comment]
Tensorflow removed in version 3.0. It should work now.
