### ISSUE TITLE
error with export

### ISSUE THREAD

**Issue by albertls** [anandanand84/technicalindicators#42]
i am getting this error 
(function (exports, require, module, __filename, __dirname) { export { sma, SMA } from './moving_averages/SMA';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/albert/Downloads/poloniex-trade-bot-master/indicators/emasma.js:4:16)
    at Module._compile (module.js:541:32)

i tested on several versions of node and OS systems!

**Comment by anandanand84** [comment]
Can you give more details on how you are using, are you using some kind of bundler? Here is the working example from tonic dev.

https://runkit.com/anandaravindan/test-techincalindicators-issue-42

**Comment by albertls** [comment]
running your example a get the same error

root@srv01:~/poloniex-trade-bot# nodejs a.js 
/root/poloniex-trade-bot/node_modules/technicalindicators/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { export { sma, SMA } from './moving_averages/SMA';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/poloniex-trade-bot/a.js:2:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
root@srv01:~/poloniex-trade-bot#

**Comment by anandanand84** [comment]
Which version of techincalindicators and nodejs are you using?  with latest version the techincalindicators packages should be loaded from dist/browser.js and not from lib/index.js

**Comment by albertls** [comment]
i am loading like your example
var sma =require('technicalindicators').sma

**Comment by anandanand84** [comment]
Can you tell the technicalindicators version in package.json?

**Comment by albertls** [comment]
root@srv01:~/poloniex-trade-bot/node_modules/technicalindicators# cat package.json 
{
  "_args": [
    [
      {
        "raw": "technicalindicators@0.2.x",
        "scope": null,
        "escapedName": "technicalindicators",
        "name": "technicalindicators",
        "rawSpec": "0.2.x",
        "spec": ">=0.2.0 <0.3.0",
        "type": "range"
      },
      "/root/poloniex-trade-bot"
    ]
  ],
  "_from": "technicalindicators@>=0.2.0 <0.3.0",
  "_id": "technicalindicators@0.2.26",
  "_inCache": true,
  "_location": "/technicalindicators",
  "_nodeVersion": "7.6.0",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/technicalindicators-0.2.26.tgz_1494556007418_0.002519107423722744"
  },

**Comment by anandanand84** [comment]
I think you are using an older version and the problem is with the exact version 0.2.26 can you try with @1.0.0 version or 0.2.25?

**Comment by albertls** [comment]
how i can obtain those versions?

**Comment by anandanand84** [comment]
I have unpublished the version 0.2.26 remove your node_modules directory, edit your package.json to point to 1.0.0 and run npm install
